# Base configs
baseurl: "https://saki007ster.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "PHOTOS by Saket Kumar"
subtitle: "See the world through my eyes!"
author: "Saket Kumar"
bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/saki007ster\">fork me on github</a> ;)"
web_design: "SK"
social_urls:
  facebook: "https://www.facebook.com/er.saketkumar"
  twitter: "https://www.twitter.com/saket_kmr"
  linkedin: "linkedin.com/in/saket-kumar-9a985b17"
  github: "https://www.github.com/saki007ster"
  